/* وصّلني - نسخة موسعة: Frontend + Supabase عند توفره + وضع تجريبي محلي */
(function(){
'use strict';
const SUPABASE_URL='https://hgbcyhzeuozlurfhsnbh.supabase.co';
const SUPABASE_KEY='sb_publishable_FZQjKJxfbcbuUGiykdmMZQ_OoB0Pp78';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=n=>Number(n||0).toLocaleString('ar-IQ')+' د.ع';
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();
let sb=null, online=false, restaurants=[], cart=JSON.parse(localStorage.getItem('wasselni_cart')||'[]');
const favs=new Set(JSON.parse(localStorage.getItem('wasselni_favs')||'[]'));
const profile=()=>JSON.parse(localStorage.getItem('wasselni_profile')||'{}');
const demoRestaurants=[
['kfc','KFC','دجاج ووجبات سريعة','دجاج','1500'],['mcd','McDonald’s','برغر ووجبات سريعة','برغر','1500'],['pizza-hut','Pizza Hut','بيتزا ومقبلات','بيتزا','2000'],['hardees','هارديز','برغر ووجبات سريعة','برغر','1500'],['burger-king','Burger King','برغر','برغر','1500'],['firefly','فاير فلاي برغر','برغر، دجاج وأجنحة','برغر','1000'],['jiter','جيتر جيكن','دجاج مقلي وبيتزا','دجاج','1000'],['99grill','99 جريل','برغر ودجاج','برغر','1000'],['snek77','سناك 77','وجبات سريعة','سندويشات','1000'],['cowboy','كاوبوي كمب','برغر ومشويات','مشويات','1000'],['khafayef','بيتزا و لحم بعجين خفايف','بيتزا','بيتزا','1000'],['falafel-lebanon','فلافل لبنان','فلافل ووجبات سريعة','فلافل','750'],['falafel-dam','فلافل الدمشقي','فلافل وسندويشات','فلافل','750'],['jkn-town','جكن تاون','وجبات سريعة ودجاج','دجاج','1000'],['west','ويست بركر','برغر ووجبات سريعة','برغر','1000'],['jkn-deep','جكن ديب','دجاج ووجبات سريعة','دجاج','1000'],['khan-basha','خان الباشا','مندي وأكلات عربية','عربي','1500'],['saj-beirut','ساج وفلافل بيروت','سندويشات وفلافل','سندويشات','1000'],['cost','كوست بركر','برغر وسندويشات','برغر','1000'],['abu-hamoudi','أبو حمودي السوري','عربي وبيتزا','عربي','1000'],['shawarma-abdali','شاورما العبدلي','شاورما ووجبات سريعة','شاورما','1000'],['alawi','مطعم علاوي','برغر ودجاج','برغر','1000'],['hadramout','مندي حضر موت اليمني','مندي ودجاج','مندي','1500'],['650','650','وجبات سريعة وعالمي','عالمي','1000'],['super-chicken','سوبر تشكن','دجاج مقلي','دجاج','1000'],['fast-meal','الوجبة السريعة','عربي ودجاج','عربي','1000'],['wasam','وسام أبو المحشي','عربي ودجاج','عربي','1000'],['kass-w-lia','كص ولية','وجبات عراقية سريعة','عراقي','1000'],['mandi-mousawi','مندي الموسوي','مندي وأكلات عربية','مندي','1500'],['bas-biryani','بس برياني','برياني عراقي','عراقي','1000'],['fried-chicken','فرايد تشكين','دجاج مقلي','دجاج','1000'],['saj-badea','ساج البديع','وجبات سريعة','سندويشات','1000'],['sindarella','مطعم سندريلا','عالمي','عالمي','1000'],['hadeez','هاديز','برغر ودجاج','برغر','1000'],['smash','مطعم سماش برجر','برغر وبيتزا','برغر','1000'],['kashmish','مطعم الكشمش','كردي','كردي','1500'],['hamdeel','مطعم همديل','كباب ومشويات','مشويات','1500'],['levant','مطعم ليفانت','مشويات ولبناني','لبناني','1500'],['roubin','روبين كنافة','حلويات وكريبات','حلويات','1000'],['don-gennaro','دون جينارو','إيطالي وبيتزا وباستا','إيطالي','1500'],['donut-world','دونت ورلد','دونات وحلويات','حلويات','1000'],['jaz','جاز','عالمي','عالمي','1000'],['chocolate-house','جوكيليت هاوس','كيك وحلويات','حلويات','1000'],['tasty-iranian','مطعم تيستي','إيراني وكباب','كباب','1500'],['najjar','مطعم كباب نجار','كباب ومشويات','كباب','1500'],['diet-meal','دايت ميل','صحي وسندويشات','صحي','1000'],['abu-shihab','أبو شهاب 60 م','كردي ومشويات','كردي','1500'],['two-in-one','2 في 1','برغر وبيتزا','برغر','1000']
].map((x,i)=>({id:x[0],name:x[1],description:x[2],category:x[3],delivery_fee:+x[4],rating:(4+(i%10)/10).toFixed(1),eta:15+(i%6)*4,min_order:5000,featured:i<8,offer:i%5===0,open:true}));
const demoProducts={};
function productsFor(r){if(demoProducts[r.id])return demoProducts[r.id];const base=[['وجبة '+r.category,12000],['وجبة كومبو',15000],['ساندويچ مميز',9000],['بطاطا ومشروب',6500],['وجبة عائلية',28000],['صوص إضافي',1500]];demoProducts[r.id]=base.map((p,i)=>({id:r.id+'-'+i,name:p[0],description:'اختيار طيب من '+r.name,price:p[1]+(r.id.length%4)*500,available:true}));return demoProducts[r.id]}
function saveCart(){localStorage.setItem('wasselni_cart',JSON.stringify(cart));badge()}
function badge(){document.querySelectorAll('[data-cart-count]').forEach(x=>x.textContent=cart.reduce((a,b)=>a+b.qty,0))}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
function saveFavs(){localStorage.setItem('wasselni_favs',JSON.stringify([...favs]))}
function layout(title,body){document.title=title+' - وصّلني';document.body.innerHTML=`<header class="top"><a class="brand" href="./index.html">وصّلني</a><nav><a href="./index.html">الرئيسية</a><a href="./restaurants.html">المطاعم</a><a href="./orders.html">طلباتي</a><a href="./support.html">الدعم</a><a href="./account.html">حسابي</a><a class="cart-link" href="./cart.html">السلة <b data-cart-count>0</b></a></nav></header><main class="container">${body}</main><footer>وصّلني • طلب طعام وتوصيل في بغداد • <a href="./login.html">الدخول الداخلي</a></footer>`;badge()}
async function loadSupabase(){try{await new Promise((resolve,reject)=>{if(window.supabase)return resolve();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);online=true}catch(e){online=false}}
async function getRestaurants(){if(online){const {data,error}=await sb.from('restaurants').select('*').order('created_at',{ascending:true});if(!error&&data?.length){restaurants=data.map(r=>({...r,category:r.category||'مطاعم',rating:r.rating||'4.5',eta:r.eta||25,open:r.is_open!==false}));return restaurants}}restaurants=demoRestaurants;return restaurants}
function restaurantCard(r){return `<article class="card restaurant-card"><a href="./restaurant.html?id=${encodeURIComponent(r.id)}" class="card-main"><div class="thumb">🍽️</div><div class="grow"><div class="card-title"><h3>${esc(r.name)}</h3><button class="heart" data-fav="${esc(r.id)}">${favs.has(String(r.id))?'♥':'♡'}</button></div><p>${esc(r.description||r.category||'مطعم')}</p><div class="meta"><span>⭐ ${esc(r.rating||'4.5')}</span><span>⏱️ ${esc(r.eta||25)} د</span><span>${money(r.delivery_fee||0)}</span></div></div></a></article>`}
async function home(){await getRestaurants();const featured=restaurants.filter(r=>r.featured||r.offer).slice(0,10);layout('الرئيسية',`<section class="hero"><div><span class="pill">بغداد • وصّلني</span><h1>كل مطاعمك بمكان واحد</h1><p>تصفح، اختار، اطلب، تابع المندوب، وتواصل مع الدعم من نفس المنصة.</p><div class="hero-actions"><a class="btn" href="./restaurants.html">ابدأ الطلب</a><a class="btn secondary" href="./restaurants.html?offers=1">العروض</a></div></div><div class="hero-art">🛵<small>توصيل سريع</small></div></section><div class="section-head"><h2>شنو تشتهي؟</h2><a href="./restaurants.html">عرض الكل</a></div><div class="chips">${['برغر','بيتزا','دجاج','شاورما','عراقي','مشويات','حلويات','صحي'].map(c=>`<a href="./restaurants.html?cat=${encodeURIComponent(c)}">${c}</a>`).join('')}</div><div class="section-head"><h2>مطاعم وعروض</h2><a href="./restaurants.html">كل المطاعم</a></div><div class="grid">${featured.map(restaurantCard).join('')}</div>`);bindFavs()}
async function restaurantsPage(){await getRestaurants();layout('المطاعم',`<div class="section-head"><div><h1>مطاعم بغداد</h1><p class="muted">كتالوج تجريبي موسع قابل للربط بقاعدة بيانات المطاعم الفعلية.</p></div></div><div class="toolbar"><input id="search" class="input" placeholder="ابحث عن مطعم أو مطبخ..."><select id="sort" class="input"><option value="recommended">المقترحة</option><option value="rating">التقييم</option><option value="fee">رسوم التوصيل</option><option value="eta">الأسرع</option></select></div><div class="chips small">${['الكل','عروض','برغر','بيتزا','دجاج','شاورما','عراقي','مشويات','حلويات','صحي','فلافل'].map(c=>`<button data-cat="${c}">${c}</button>`).join('')}</div><div id="restaurantGrid" class="grid"></div>`);const q=new URLSearchParams(location.search);renderRestaurants(q.get('cat')||'الكل',q.get('offers')==='1');$('#search').oninput=()=>renderRestaurants(document.querySelector('.chips button.active')?.dataset.cat||'الكل',false);$('#sort').onchange=()=>renderRestaurants(document.querySelector('.chips button.active')?.dataset.cat||'الكل',false);document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-cat]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderRestaurants(b.dataset.cat,false)});}
function renderRestaurants(cat='الكل',offers=false){const q=($('#search')?.value||'').trim().toLowerCase();let a=restaurants.filter(r=>(cat==='الكل'||r.category===cat)&&(!offers||r.offer)&&((r.name+' '+r.description+' '+r.category).toLowerCase().includes(q)));const s=$('#sort')?.value||'recommended';if(s==='rating')a.sort((x,y)=>y.rating-x.rating);if(s==='fee')a.sort((x,y)=>x.delivery_fee-y.delivery_fee);if(s==='eta')a.sort((x,y)=>x.eta-y.eta);$('#restaurantGrid').innerHTML=a.map(restaurantCard).join('')||'<div class="empty">ماكو مطاعم مطابقة.</div>';bindFavs()}
function bindFavs(){document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const id=String(b.dataset.fav);favs.has(id)?favs.delete(id):favs.add(id);saveFavs();b.textContent=favs.has(id)?'♥':'♡'})}
async function restaurantPage(){await getRestaurants();const id=new URLSearchParams(location.search).get('id');const r=restaurants.find(x=>String(x.id)===String(id))||restaurants[0];if(!r){location.href='./restaurants.html';return}const ps=productsFor(r);layout(r.name,`<div class="restaurant-cover"><div class="thumb big">🍽️</div><div class="grow"><span class="pill">${r.open===false?'مغلق الآن':'مفتوح الآن'}</span><h1>${esc(r.name)}</h1><p>${esc(r.description||'')}</p><div class="meta"><span>⭐ ${r.rating}</span><span>⏱️ ${r.eta} دقيقة</span><span>توصيل ${money(r.delivery_fee)}</span><span>الحد الأدنى ${money(r.min_order||0)}</span></div></div><button class="heart large" data-fav="${esc(r.id)}">${favs.has(String(r.id))?'♥':'♡'}</button></div><div class="chips small">${['الأكثر طلباً','وجبات','سندويچات','إضافات'].map(x=>`<span>${x}</span>`).join('')}</div><div class="product-grid">${ps.map(p=>`<article class="product"><div class="thumb product-img">🍴</div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><strong>${money(p.price)}</strong><button class="btn full" data-add="${esc(p.id)}">أضف للسلة</button></article>`).join('')}</div>`);bindFavs();document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const p=ps.find(x=>x.id===b.dataset.add);addProduct(p,r)})}
function addProduct(p,r){if(cart.length&&String(cart[0].restaurant_id)!==String(r.id)){if(!confirm('السلة تحتوي أصناف من مطعم آخر. تريد تبديل المطعم؟'))return;cart=[]}const x=cart.find(i=>i.product_id===p.id);if(x)x.qty++;else cart.push({product_id:p.id,restaurant_id:r.id,restaurant_name:r.name,name:p.name,price:Number(p.price),qty:1});saveCart();toast('تمت إضافة الصنف للسلة')}
function cartTotals(){const subtotal=cart.reduce((a,i)=>a+i.price*i.qty,0);const r=restaurants.find(x=>String(x.id)===String(cart[0]?.restaurant_id));const fee=Number(r?.delivery_fee||0);return {subtotal,fee,total:subtotal+fee,r}}
function cartPage(){const t=cartTotals();layout('السلة',`<div class="section-head"><h1>السلة</h1><a href="./restaurants.html">أضف أصناف</a></div>${cart.length?`<div class="list">${cart.map((i,n)=>`<div class="row"><div><b>${esc(i.name)}</b><small>${esc(i.restaurant_name)} • ${money(i.price)}</small></div><div class="qty"><button data-dec="${n}">−</button><span>${i.qty}</span><button data-inc="${n}">+</button></div><strong>${money(i.price*i.qty)}</strong></div>`).join('')}</div><div class="summary"><div><span>المجموع الفرعي</span><b>${money(t.subtotal)}</b></div><div><span>التوصيل</span><b>${money(t.fee)}</b></div><div class="grand"><span>الإجمالي</span><b>${money(t.total)}</b></div></div><a class="btn full" href="./login.html?next=checkout">إكمال الطلب</a>`:'<div class="empty"><div class="empty-icon">🛒</div><h2>السلة فارغة</h2><p>اختار مطعم وابدأ طلبك.</p><a class="btn" href="./restaurants.html">تصفح المطاعم</a></div>'}`);document.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>{cart[+b.dataset.inc].qty++;saveCart();cartPage()});document.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>{const i=+b.dataset.dec;cart[i].qty--;if(cart[i].qty<=0)cart.splice(i,1);saveCart();cartPage()})}
async function loginPage(){layout('تسجيل الدخول',`<div class="auth"><div class="auth-icon">🔐</div><h1>أهلاً بيك</h1><p class="muted">سجل دخول حتى تحفظ عناوينك وطلباتك.</p><input id="email" class="input" type="email" placeholder="الإيميل"><input id="password" class="input" type="password" placeholder="كلمة المرور"><input id="name" class="input" placeholder="الاسم عند التسجيل"><button id="signin" class="btn full">دخول</button><button id="signup" class="btn secondary full">إنشاء حساب</button><p id="msg"></p></div>`);$('#signin').onclick=async()=>{if(online){const {error}=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)return msg(error.message)}localStorage.setItem('wasselni_profile',JSON.stringify({name:$('#name').value||$('#email').value.split('@')[0],email:$('#email').value}));location.href=new URLSearchParams(location.search).get('next')==='checkout'?'./checkout.html':'./account.html'};$('#signup').onclick=async()=>{if(online){const {error}=await sb.auth.signUp({email:$('#email').value,password:$('#password').value,options:{data:{full_name:$('#name').value}}});if(error)return msg(error.message)}localStorage.setItem('wasselni_profile',JSON.stringify({name:$('#name').value,email:$('#email').value}));msg('تم إنشاء الحساب. تگدر تكمل التجربة هسه.');};}
function msg(x){if($('#msg'))$('#msg').textContent=x}
async function currentUser(){if(online){const {data:{user}}=await sb.auth.getUser();if(user)return user}const p=profile();return p.email?p:null}
async function checkout(){await getRestaurants();const user=await currentUser();if(!user){location.href='./login.html?next=checkout';return}if(!cart.length){location.href='./cart.html';return}const t=cartTotals();layout('تأكيد الطلب',`<div class="checkout-grid"><div class="auth"><h1>تأكيد الطلب</h1><label>الاسم</label><input id="name" class="input" value="${esc(user.user_metadata?.full_name||user.name||'')}" placeholder="الاسم"><label>رقم الهاتف</label><input id="phone" class="input" placeholder="07xxxxxxxxx"><label>عنوان التوصيل</label><textarea id="address" class="input" rows="4" placeholder="المنطقة، الشارع، أقرب نقطة دالة"></textarea><label>طريقة الدفع</label><select id="payment" class="input"><option value="cash">كاش عند الاستلام</option><option value="mastercard">Visa / Mastercard</option></select><label>ملاحظات</label><textarea id="notes" class="input" rows="3" placeholder="مثلاً: بدون بصل"></textarea><button id="place" class="btn full">تأكيد الطلب • ${money(t.total)}</button><p id="msg"></p></div><aside class="order-preview"><h2>ملخص الطلب</h2><p><b>${esc(t.r?.name||'المطعم')}</b></p>${cart.map(i=>`<div class="mini"><span>${esc(i.name)} × ${i.qty}</span><b>${money(i.price*i.qty)}</b></div>`).join('')}<hr><div class="mini"><span>التوصيل</span><b>${money(t.fee)}</b></div><div class="grand"><span>الإجمالي</span><b>${money(t.total)}</b></div></aside></div>`);$('#place').onclick=()=>placeOrder(user,t)}
async function placeOrder(user,t){const name=$('#name').value.trim(),phone=$('#phone').value.trim(),address=$('#address').value.trim();if(!name||!phone||!address)return msg('كمل الاسم والرقم والعنوان أولاً.');const localOrder={id:'W'+Date.now(),created_at:new Date().toISOString(),restaurant_id:t.r.id,restaurant_name:t.r.name,customer_name:name,customer_phone:phone,delivery_address:address,payment_method:$('#payment').value,notes:$('#notes').value,subtotal:t.subtotal,delivery_fee:t.fee,total:t.total,status:'pending',items:cart.map(x=>({...x})),history:[{status:'pending',at:new Date().toISOString()}]};if(online&&user.id){const payload={customer_id:user.id,restaurant_id:t.r.id,customer_name:name,customer_phone:phone,delivery_address:address,payment_method:localOrder.payment_method,status:'pending',subtotal:t.subtotal,delivery_fee:t.fee,total:t.total,notes:localOrder.notes};const {data:o,error}=await sb.from('orders').insert(payload).select().single();if(!error){await sb.from('order_items').insert(cart.map(i=>({order_id:o.id,product_id:i.product_id,product_name:i.name,price:i.price,quantity:i.qty})));localOrder.id=o.id}}const orders=JSON.parse(localStorage.getItem('wasselni_orders')||'[]');orders.unshift(localOrder);localStorage.setItem('wasselni_orders',JSON.stringify(orders));cart=[];saveCart();location.href='./orders.html?id='+encodeURIComponent(localOrder.id)}
async function ordersPage(){await getRestaurants();const user=await currentUser();if(!user){location.href='./login.html';return}let orders=JSON.parse(localStorage.getItem('wasselni_orders')||'[]');if(online&&user.id){const {data}=await sb.from('orders').select('*, restaurants(name)').eq('customer_id',user.id).order('created_at',{ascending:false});if(data?.length)orders=data.map(o=>({...o,restaurant_name:o.restaurants?.name||'مطعم'}))}const id=new URLSearchParams(location.search).get('id');if(id){const o=orders.find(x=>String(x.id)===String(id));if(o)return orderDetails(o)}layout('طلباتي',`<div class="section-head"><h1>طلباتي</h1><a href="./restaurants.html">طلب جديد</a></div><div class="list">${orders.map(o=>`<a class="order" href="./orders.html?id=${encodeURIComponent(o.id)}"><div><b>${esc(o.restaurant_name||'مطعم')}</b><small>${new Date(o.created_at).toLocaleString('ar-IQ')}</small></div><span class="status ${esc(o.status)}">${statusText(o.status)}</span><strong>${money(o.total)}</strong></a>`).join('')||'<div class="empty">ما عندك طلبات بعد.</div>'}</div>`)}
function statusText(s){return ({pending:'بانتظار المطعم',confirmed:'تم تأكيد الطلب',preparing:'قيد التحضير',ready:'جاهز للاستلام',picked_up:'مع المندوب',on_the_way:'بالطريق إلك',delivered:'تم التوصيل',cancelled:'ملغي'})[s]||s}
function orderDetails(o){const statuses=['pending','confirmed','preparing','picked_up','on_the_way','delivered'];let current=statuses.indexOf(o.status);if(current<0)current=0;layout('تتبع الطلب',`<div class="track-head"><div><span class="pill">${statusText(o.status)}</span><h1>طلب #${esc(String(o.id).slice(-8))}</h1><p>${esc(o.restaurant_name||'المطعم')}</p></div><strong>${money(o.total)}</strong></div><div class="timeline">${statuses.map((s,i)=>`<div class="step ${i<=current?'done':''}"><span>${i<=current?'✓':'○'}</span><div><b>${statusText(s)}</b><small>${i<=current?'تم تحديث الحالة':'بانتظار التحديث'}</small></div></div>`).join('')}</div><div class="card"><h2>تفاصيل الطلب</h2>${(o.items||[]).map(i=>`<div class="mini"><span>${esc(i.name||i.product_name)} × ${i.qty||i.quantity}</span><b>${money((i.price||0)*(i.qty||i.quantity))}</b></div>`).join('')}<hr><div class="mini"><span>التوصيل</span><b>${money(o.delivery_fee)}</b></div><div class="grand"><span>الإجمالي</span><b>${money(o.total)}</b></div></div><div class="hero compact"><h2>تحتاج مساعدة؟</h2><p>فريق خدمة الزبائن موجود لمساعدتك بخصوص هذا الطلب.</p><a class="btn" href="./support.html?order=${encodeURIComponent(o.id)}">فتح الدعم</a></div>`)}
async function accountPage(){const user=await currentUser();if(!user){location.href='./login.html';return}const p=profile();const orders=JSON.parse(localStorage.getItem('wasselni_orders')||'[]');layout('حسابي',`<div class="profile"><div class="avatar">👤</div><h1>${esc(p.name||user.user_metadata?.full_name||user.email||'حسابي')}</h1><p>${esc(p.email||user.email||'')}</p><div class="profile-grid"><div><b>${orders.length}</b><small>طلب</small></div><div><b>${favs.size}</b><small>مفضل</small></div><div><b>${money(0)}</b><small>رصيد</small></div></div><a class="btn full" href="./orders.html">طلباتي</a><a class="btn secondary full" href="./restaurants.html">المطاعم والمفضلة</a><button id="logout" class="btn ghost full">تسجيل خروج</button></div>`);$('#logout').onclick=async()=>{if(online)await sb.auth.signOut();localStorage.removeItem('wasselni_profile');location.href='./index.html'}}
async function supportPage(){const user=await currentUser();layout('خدمة العملاء',`<div class="support"><div class="support-head"><div class="avatar">🎧</div><div><h1>خدمة العملاء</h1><p>نساعدك بخصوص الطلبات، الدفع، التوصيل والمشاكل.</p></div></div><div id="chat" class="chat">${JSON.parse(localStorage.getItem('wasselni_chat')||'[]').map(m=>`<div class="bubble ${m.from==='user'?'mine':''}">${esc(m.text)}<small>${esc(m.time||'')}</small></div>`).join('')||'<div class="empty">هلا بيك 🌟 اكتب مشكلتك وراح نتابعها.</div>'}</div><div class="chatbar"><input id="chatInput" class="input" placeholder="اكتب رسالتك..."><button id="send" class="btn">إرسال</button></div>`);$('#send').onclick=sendChat;$('#chatInput').onkeydown=e=>{if(e.key==='Enter')sendChat()}}
function sendChat(){const input=$('#chatInput');if(!input.value.trim())return;const a=JSON.parse(localStorage.getItem('wasselni_chat')||'[]');a.push({from:'user',text:input.value,time:new Date().toLocaleTimeString('ar-IQ',{hour:'2-digit',minute:'2-digit'})});a.push({from:'agent',text:'وصلت رسالتك. أحد موظفي الدعم راح يتابع وياك قريباً.',time:new Date().toLocaleTimeString('ar-IQ',{hour:'2-digit',minute:'2-digit'})});localStorage.setItem('wasselni_chat',JSON.stringify(a));supportPage()}
async function adminPage(){const orders=JSON.parse(localStorage.getItem('wasselni_orders')||'[]');await getRestaurants();layout('الإدارة',`<div class="section-head"><h1>لوحة الإدارة</h1><span class="pill">وضع ${online?'Supabase':'تجريبي محلي'}</span></div><div class="stats"><div>المطاعم<strong>${restaurants.length}</strong></div><div>الطلبات<strong>${orders.length}</strong></div><div>المبيعات<strong>${money(orders.reduce((a,o)=>a+Number(o.total||0),0))}</strong></div></div><div class="grid two"><div class="card"><h2>إدارة المطاعم</h2><p>إضافة، إيقاف، تعديل المنيو والعروض عند ربط لوحة الإدارة بقاعدة البيانات.</p><a class="btn" href="./restaurants.html">مشاهدة المطاعم</a></div><div class="card"><h2>خدمة العملاء</h2><p>مركز موحد لمتابعة المحادثات والشكاوى والطلبات.</p><a class="btn" href="./support.html">فتح الدعم</a></div></div>`)}
function restaurantPanel(){layout('لوحة المطعم',`<div class="section-head"><h1>لوحة المطعم</h1><span class="pill">جاهزة للتوصيل بقاعدة البيانات</span></div><div class="stats"><div>طلبات جديدة<strong>0</strong></div><div>قيد التحضير<strong>0</strong></div><div>مبيعات اليوم<strong>0</strong></div></div><div class="card"><h2>سير العمل</h2><div class="timeline"><div class="step done"><span>1</span><div><b>استلام الطلب</b><small>يصل فوراً من الزبون</small></div></div><div class="step"><span>2</span><div><b>قبول وتحضير</b><small>تحديث حالة الطلب</small></div></div><div class="step"><span>3</span><div><b>جاهز للمندوب</b><small>إسناد الطلب للتوصيل</small></div></div></div></div>`)}
function driverPage(){layout('لوحة المندوب',`<div class="section-head"><h1>لوحة المندوب</h1><span class="pill">تتبع مباشر جاهز للربط</span></div><div class="card"><h2>رحلاتي</h2><div class="empty">عند ربط نظام المندوب سيتم عرض الطلبات المسندة، الملاحة، إثبات التسليم، وحالة الرحلة هنا.</div></div>`)}
async function boot(){try{await loadSupabase();const p=location.pathname.split('/').pop()||'index.html';if(p==='index.html')return home();if(p==='restaurants.html')return restaurantsPage();if(p==='restaurant.html')return restaurantPage();if(p==='cart.html')return cartPage();if(p==='login.html')return loginPage();if(p==='checkout.html')return checkout();if(p==='orders.html')return ordersPage();if(p==='account.html')return accountPage();if(p==='support.html')return supportPage();if(p==='admin.html')return adminPage();if(p==='restaurant-panel.html')return restaurantPanel();if(p==='driver.html')return driverPage();return home()}catch(e){console.error(e);document.body.innerHTML=`<main class="container"><div class="error"><h1>صار خطأ</h1><p>${esc(e.message||e)}</p><a class="btn" href="./index.html">العودة للرئيسية</a></div></main>`}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
