const R=[{id:1,name:'مذاق بغداد',emoji:'🍔',rating:4.8,time:'25-35 دقيقة',fee:2000,items:[{id:101,name:'برگر كلاسيك',desc:'لحم وجبن وخس وصوص خاص',price:7500,emoji:'🍔'},{id:102,name:'تشكن برگر',desc:'دجاج مقرمش وجبن',price:7000,emoji:'🍗'}]},{id:2,name:'بيت البيتزا',emoji:'🍕',rating:4.7,time:'30-40 دقيقة',fee:2500,items:[{id:201,name:'بيتزا خضار',desc:'خضار طازجة وجبن',price:9000,emoji:'🍕'},{id:202,name:'بيتزا دجاج',desc:'دجاج وفطر وجبن',price:10000,emoji:'🍕'}]},{id:3,name:'مشويات الشرق',emoji:'🥩',rating:4.9,time:'35-45 دقيقة',fee:2000,items:[{id:301,name:'كباب عراقي',desc:'كباب مشوي مع خبز ومقبلات',price:12000,emoji:'🥩'},{id:302,name:'تكة دجاج',desc:'دجاج متبل ومشوي',price:11000,emoji:'🍢'}]}];
const money=n=>n.toLocaleString('ar-IQ')+' د.ع'; const getCart=()=>JSON.parse(localStorage.cart||'[]'); const setCart=x=>localStorage.cart=JSON.stringify(x); const getOrders=()=>JSON.parse(localStorage.orders||'[]'); const setOrders=x=>localStorage.orders=JSON.stringify(x); const count=()=>getCart().reduce((a,b)=>a+b.qty,0);
function shell(body,title='وصّلني',active='home'){document.getElementById('app').innerHTML=`<div class="app"><header class="top"><b class="brand">${title}</b><button class="btn light" onclick="location.href='cart.html'">🛒 ${count()}</button></header><main class="main">${body}</main><nav class="bottom"><a class="${active==='home'?'active':''}" href="index.html">🏠<span>الرئيسية</span></a><a class="${active==='rest'?'active':''}" href="restaurants.html">🍽️<span>المطاعم</span></a><a class="${active==='orders'?'active':''}" href="orders.html">📦<span>طلباتي</span></a><a class="${active==='account'?'active':''}" href="account.html">👤<span>حسابي</span></a></nav></div>`}
function card(r){return `<article class="card rest" onclick="location.href='restaurant.html?id=${r.id}'"><div class="cover">${r.emoji}</div><div><h3>${r.name}</h3><span class="muted">⭐ ${r.rating} · ${r.time}</span><br><span class="muted">توصيل ${money(r.fee)}</span></div></article>`}
function home(){shell(`<section class="hero"><small>أهلاً بك 👋</small><h1>شنو تشتهي اليوم؟</h1><p>اطلب من مطاعمك المفضلة وخلي الباقي علينا.</p></section><div class="search">🔎 <input id="q" placeholder="ابحث عن مطعم..." oninput="draw()"></div><h2>المطاعم</h2><div class="grid" id="list"></div>`);draw()}
function draw(){let q=(document.getElementById('q')?.value||'').toLowerCase();document.getElementById('list').innerHTML=R.filter(x=>x.name.toLowerCase().includes(q)).map(card).join('')}
function restaurantsPage(){shell(`<div class="search">🔎 <input id="q" placeholder="ابحث عن مطعم..." oninput="drawR()"></div><div class="grid" id="list"></div>`,'المطاعم','rest');drawR()} function drawR(){let q=(document.getElementById('q')?.value||'').toLowerCase();document.getElementById('list').innerHTML=R.filter(x=>x.name.toLowerCase().includes(q)).map(card).join('')}
function restaurantPage(){let id=+(new URLSearchParams(location.search).get('id')||1),r=R.find(x=>x.id===id)||R[0];shell(`<div class="card"><div class="row"><div><h1>${r.name}</h1><p class="muted">⭐ ${r.rating} · ${r.time} · توصيل ${money(r.fee)}</p></div><b style="font-size:45px">${r.emoji}</b></div></div><h2>المنيو</h2>${r.items.map(i=>`<div class="item menu"><div class="food">${i.emoji}</div><div class="grow"><b>${i.name}</b><p class="muted">${i.desc}</p><div class="price">${money(i.price)}</div></div><button class="btn dark" onclick='add(${JSON.stringify(i)})'>أضف</button></div>`).join('')}`,'وصّلني','rest')}
function add(i){let c=getCart(),x=c.find(a=>a.id===i.id);x?x.qty++:c.push({...i,qty:1});setCart(c);alert('تمت الإضافة للسلة ✅')}
function cartPage(){let c=getCart();if(!c.length){shell(`<div class="empty">🛒<h2>السلة فارغة</h2><a href="restaurants.html">تصفح المطاعم</a></div>`,'السلة');return}let total=c.reduce((s,x)=>s+x.price*x.qty,0);shell(`${c.map(x=>`<div class="item menu"><div class="food">${x.emoji}</div><div class="grow"><b>${x.name}</b><div>${money(x.price)}</div></div><button class="btn light" onclick="change(${x.id},-1)">−</button>${x.qty}<button class="btn light" onclick="change(${x.id},1)">+</button></div>`).join('')}<div class="card row"><b>المجموع</b><b>${money(total)}</b></div><div class="card form"><h2>معلومات التوصيل</h2><input id="name" placeholder="الاسم"><input id="phone" placeholder="رقم الهاتف"><textarea id="address" rows="3" placeholder="العنوان بالتفصيل"></textarea><h3>طريقة الدفع</h3><div class="pay"><label><input type="radio" name="pay" value="cash" checked> 💵 كاش</label><label><input type="radio" name="pay" value="card"> 💳 ماستر</label></div><br><button class="btn dark" style="width:100%" onclick="place()">تأكيد الطلب</button></div>`,'السلة')}
function change(id,d){let c=getCart(),x=c.find(a=>a.id===id);x.qty+=d;setCart(c.filter(a=>a.qty>0));cartPage()}
function place(){let n=document.getElementById('name').value.trim(),p=document.getElementById('phone').value.trim(),a=document.getElementById('address').value.trim();if(!n||!p||!a)return alert('كمل معلومات التوصيل أولاً');let items=getCart(),o=getOrders();o.unshift({id:'WD'+Date.now().toString().slice(-7),name:n,phone:p,address:a,pay:document.querySelector('[name=pay]:checked').value,total:items.reduce((s,x)=>s+x.price*x.qty,0),items,status:'جديد',date:new Date().toLocaleString('ar-IQ')});setOrders(o);localStorage.removeItem('cart');location.href='orders.html'}
function ordersPage(){let o=getOrders();shell(o.length?o.map(x=>`<article class="order"><div class="row"><b>#${x.id}</b><span class="status">${x.status}</span></div><p>${x.items.map(i=>i.name+' × '+i.qty).join('، ')}</p><b>${money(x.total)}</b><p class="muted">${x.date}</p></article>`).join(''):`<div class="empty">📦<h2>لا توجد طلبات</h2><a href="restaurants.html">ابدأ الطلب</a></div>`,'طلباتي','orders')}
function loginPage(){document.getElementById('app').innerHTML=`<div class="app"><main class="main"><section class="hero"><h1>وصّلني V2</h1><p>دخول الأنظمة الداخلية</p></section><div class="card form"><select id="role"><option value="admin">الإدارة</option><option value="restaurant">المطعم</option><option value="driver">المندوب</option></select><input id="pin" type="password" placeholder="PIN تجريبي: 1234"><button class="btn dark" style="width:100%" onclick="login()">دخول</button></div></main></div>`} function login(){if(document.getElementById('pin').value!=='1234')return alert('PIN غير صحيح');let r=document.getElementById('role').value;location.href=r==='admin'?'admin.html':r==='restaurant'?'restaurant-panel.html':'driver.html'}
function action(id,status){let o=getOrders(),x=o.find(a=>a.id===id);if(x){x.status=status;setOrders(o);location.reload()}}
function orderBox(x,btn){return `<article class="order"><div class="row"><b>#${x.id}</b><span class="status">${x.status}</span></div><p>${x.items.map(i=>i.name+' × '+i.qty).join('، ')}</p><p class="muted">${x.name} · ${x.phone}<br>${x.address}</p><b>${money(x.total)}</b><br>${btn||''}</article>`}
function adminPage(){let o=getOrders(),sales=o.reduce((s,x)=>s+x.total,0);shell(`<div class="statgrid"><div class="stat">الطلبات<h2>${o.length}</h2></div><div class="stat">المبيعات<h2>${money(sales)}</h2></div></div><h2>الإدارة</h2><div class="grid"><a class="card" href="restaurant-panel.html">🏪 لوحة المطعم</a><a class="card" href="driver.html">🛵 لوحة المندوب</a><a class="card" href="restaurants.html">🍽️ المطاعم</a><a class="card" href="orders.html">📦 طلبات الزبائن</a></div><h2>الطلبات</h2>${o.map(x=>orderBox(x)).join('')||'<div class="empty">لا توجد طلبات</div>'}`,'الإدارة')}
function restaurantPanel(){let o=getOrders();shell(`<h2>طلبات المطعم</h2>${o.map(x=>orderBox(x,x.status==='جديد'?`<button class="btn dark" onclick="action('${x.id}','قيد التحضير')">قبول وتحضير</button>`:x.status==='قيد التحضير'?`<button class="btn dark" onclick="action('${x.id}','جاهز')">جاهز للمندوب</button>`:x.status==='جاهز'?`<button class="btn light" onclick="action('${x.id}','بانتظار المندوب')">تسليم للمندوب</button>`:'')).join('')||'<div class="empty">لا توجد طلبات</div>'}`,'لوحة المطعم')}
function driverPage(){let o=getOrders();shell(`<h2>طلبات المندوب</h2>${o.map(x=>orderBox(x,x.status==='جاهز'||x.status==='بانتظار المندوب'?`<button class="btn dark" onclick="action('${x.id}','مع المندوب')">استلمت الطلب</button>`:x.status==='مع المندوب'?`<button class="btn dark" onclick="action('${x.id}','بالطريق')">بالطريق</button>`:x.status==='بالطريق'?`<button class="btn dark" onclick="action('${x.id}','تم التوصيل')">تم التوصيل</button>`:'')).join('')||'<div class="empty">لا توجد طلبات</div>'}`,'المندوب')}
function getProfile(){return JSON.parse(localStorage.profile||'{}')}
function saveProfile(){let p=getProfile();p.name=document.getElementById('profileName').value.trim();p.phone=document.getElementById('profilePhone').value.trim();p.address=document.getElementById('profileAddress').value.trim();localStorage.profile=JSON.stringify(p);document.getElementById('profileModal').remove();accountPage()}
function openProfile(){let p=getProfile();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="profileModal"><div class="modalBox"><div class="row"><h2>تعديل الحساب</h2><button class="iconBtn" onclick="document.getElementById('profileModal').remove()">✕</button></div><label>الاسم</label><input id="profileName" value="${p.name||''}" placeholder="اكتب اسمك"><label>رقم الهاتف</label><input id="profilePhone" value="${p.phone||''}" placeholder="07xxxxxxxxx"><label>العنوان الرئيسي</label><textarea id="profileAddress" rows="3" placeholder="المنطقة، الشارع، أقرب نقطة دالة">${p.address||''}</textarea><button class="btn dark full" onclick="saveProfile()">حفظ التغييرات</button></div></div>`)}
function accountPage(){let p=getProfile(),o=getOrders(),active=o.find(x=>!['تم التوصيل','ملغي'].includes(x.status));let delivered=o.filter(x=>x.status==='تم التوصيل').length;let totalSpent=o.filter(x=>x.status!=='ملغي').reduce((s,x)=>s+x.total,0);let name=p.name||'ضيفنا العزيز';let initial=(name==='ضيفنا العزيز'?'👤':name.trim().charAt(0));shell(`<section class="accountHero"><div class="avatar">${initial}</div><div class="accountInfo"><div class="eyebrow">مرحباً بك 👋</div><h1>${name}</h1><p>${p.phone||'أكمل بياناتك حتى يصير طلبك أسرع'}</p></div><button class="editCircle" onclick="openProfile()">✎</button></section>
${active?`<section class="liveOrder" onclick="location.href='orders.html'"><div class="liveTop"><span class="liveDot"></span><b>طلبك الحالي</b><span class="status">${active.status}</span></div><div class="liveBody"><div><strong>#${active.id}</strong><p>${active.items.map(i=>i.name+' × '+i.qty).join('، ')}</p></div><span class="arrow">‹</span></div><div class="progress"><span class="done"></span><span class="done"></span><span class="current"></span><span></span></div><div class="progressLabels"><span>تم الاستلام</span><span>قيد التحضير</span><span>بالطريق</span><span>وصل</span></div></section>`:''}
<div class="quickGrid"><a href="orders.html" class="quick"><span>📦</span><b>طلباتي</b><small>${o.length} طلب</small></a><a href="restaurants.html" class="quick"><span>🔁</span><b>إعادة الطلب</b><small>من طلباتك السابقة</small></a><button class="quick" onclick="openProfile()"><span>📍</span><b>عناويني</b><small>${p.address?'عنوان محفوظ':'أضف عنوانك'}</small></button><a href="cart.html" class="quick"><span>🛒</span><b>السلة</b><small>${count()} أصناف</small></a></div>
<section class="statsCard"><div><strong>${o.length}</strong><span>كل الطلبات</span></div><div><strong>${delivered}</strong><span>طلبات مستلمة</span></div><div><strong>${money(totalSpent)}</strong><span>إجمالي مشترياتك</span></div></section>
<section class="accountSection"><h2>حسابي</h2><div class="menuList"><button onclick="openProfile()"><span>👤</span><div><b>المعلومات الشخصية</b><small>الاسم ورقم الهاتف والعنوان</small></div><i>‹</i></button><button onclick="openProfile()"><span>📍</span><div><b>عنوان التوصيل</b><small>${p.address||'ما عندك عنوان محفوظ بعد'}</small></div><i>‹</i></button><button onclick="alert('الدفع الإلكتروني محفوظ كخيار أثناء إتمام الطلب حالياً')"><span>💳</span><div><b>طرق الدفع</b><small>كاش أو ماستر كارد</small></div><i>‹</i></button><button onclick="alert('العروض والكوبونات راح تتفعل مع نظام العروض')"><span>🎁</span><div><b>العروض والكوبونات</b><small>استخدم كوبونك وقت الدفع</small></div><i>‹</i></button></div></section>
<section class="accountSection"><h2>المساعدة والدعم</h2><div class="menuList"><button onclick="alert('خدمة العملاء: سيتم ربطها بالدردشة والاتصال في النسخة القادمة')"><span>💬</span><div><b>خدمة العملاء</b><small>نحن هنا لمساعدتك</small></div><i>‹</i></button><button onclick="alert('مركز المساعدة قريباً')"><span>❓</span><div><b>مركز المساعدة</b><small>الأسئلة الشائعة وحلول المشاكل</small></div><i>‹</i></button><button onclick="alert('الإعدادات قريباً')"><span>⚙️</span><div><b>الإعدادات</b><small>الإشعارات والخصوصية واللغة</small></div><i>‹</i></button></div></section>
<div class="accountFooter"><b>وصّلني</b><span>طلبك يوصل لبابك بسهولة ❤️</span><small>نسخة تجريبية V2</small></div>`,'حسابي','account')}
