const restaurants=[
{id:1,name:'مذاق بغداد',emoji:'🍔',rating:4.8,time:'25-35 دقيقة',fee:2000,cat:'برگر',items:[['برگر كلاسيك','لحم عراقي، جبن، خس، طماطة وصوص خاص',7500,'🍔'],['تشكن برگر','دجاج مقرمش، جبن وصوص البيت',7000,'🍗'],['بطاطا بالجبن','بطاطا مقرمشة مع جبن وصوص',4500,'🍟']]},
{id:2,name:'بيت البيتزا',emoji:'🍕',rating:4.7,time:'30-40 دقيقة',fee:2500,cat:'بيتزا',items:[['بيتزا خضار','خضار طازجة وجبن موزاريلا',9000,'🍕'],['بيتزا دجاج','دجاج، فطر، زيتون وجبن',10000,'🍕'],['بيتزا بيبروني','بيبروني وجبن وصوص طماطة',10500,'🍕']]},
{id:3,name:'مشويات الشرق',emoji:'🥩',rating:4.9,time:'35-45 دقيقة',fee:2000,cat:'مشويات',items:[['كباب عراقي','كباب مشوي مع خبز ومقبلات',12000,'🥩'],['تكة دجاج','دجاج متبل ومشوي على الفحم',11000,'🍢'],['ريش غنم','ريش غنم مشوية مع المقبلات',16000,'🍖']]},
{id:4,name:'بيت الشاورما',emoji:'🌯',rating:4.6,time:'20-30 دقيقة',fee:1500,cat:'شاورما',items:[['شاورما دجاج','شاورما دجاج، مخلل وثوم',6500,'🌯'],['شاورما لحم','لحم شاورما مع طحينية ومخلل',7500,'🌯'],['وجبة شاورما','ساندويچ + بطاطا + مشروب',9000,'🍱']]},
{id:5,name:'فطورنا',emoji:'🍳',rating:4.8,time:'15-25 دقيقة',fee:1500,cat:'فطور',items:[['فطور عراقي','بيض، قشطة، جبن، مربى وخبز حار',7000,'🍳'],['شكشوكة','بيض مع طماطة وفلفل',5500,'🍳'],['كاهي وقيمر','كاهي عراقي مع قيمر وعسل',6000,'🥞']]},
{id:6,name:'سويت تايم',emoji:'🍰',rating:4.7,time:'20-30 دقيقة',fee:1500,cat:'حلويات',items:[['تشيز كيك','قطعة تشيز كيك بصوص الفراولة',6500,'🍰'],['براوني','براوني شوكولاتة دافئة',5500,'🍫'],['آيس كريم','ثلاث نكهات حسب اختيارك',5000,'🍨']]}
];
const money=n=>Number(n).toLocaleString('ar-IQ')+' د.ع'; const get=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)); const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v)); const cart=()=>get('cart',[]); const orders=()=>get('orders',[]); const profile=()=>get('profile',{}); const count=()=>cart().reduce((s,x)=>s+x.qty,0);
function shell(body,title='وصّلني',active='home'){document.getElementById('app').innerHTML=`<div class="app"><header class="top"><b class="brand">${title}</b><a class="btn light" href="cart.html">🛒 ${count()}</a></header><main class="main">${body}</main><nav class="bottom"><a class="${active==='home'?'active':''}" href="index.html">🏠<span>الرئيسية</span></a><a class="${active==='rest'?'active':''}" href="restaurants.html">🍽️<span>المطاعم</span></a><a class="${active==='orders'?'active':''}" href="orders.html">📦<span>طلباتي</span></a><a class="${active==='account'?'active':''}" href="account.html">👤<span>حسابي</span></a></nav></div>`}
function restCard(r){return `<a class="card rest" href="restaurant.html?id=${r.id}"><div class="cover">${r.emoji}</div><div><h3>${r.name}</h3><div class="muted">⭐ ${r.rating} · ${r.time}</div><div class="muted">توصيل ${money(r.fee)}</div><span class="tag">${r.cat}</span></div></a>`}
function home(){shell(`<section class="hero"><small>وصّلني 🚴</small><h1>شنو تشتهي اليوم؟</h1><p>اختار مطعمك، اطلب، وخلي التوصيل علينا.</p></section><div class="search">🔎 <input id="q" placeholder="ابحث عن مطعم أو أكلة..." oninput="homeDraw()"></div><div class="chips"><button class="active">الكل</button>${['برگر','بيتزا','مشويات','شاورما','فطور','حلويات'].map(x=>`<button onclick="homeCat('${x}')">${x}</button>`).join('')}</div><h2>مطاعم قريبة ومميزة</h2><div class="grid" id="list"></div>`);homeDraw()}
function homeCat(c){let q=document.getElementById('q');q.value=c;homeDraw()}
function homeDraw(){let q=(document.getElementById('q')?.value||'').toLowerCase();let rs=restaurants.filter(r=>!q||r.name.toLowerCase().includes(q)||r.cat.toLowerCase().includes(q)||r.items.some(i=>i[0].toLowerCase().includes(q)));document.getElementById('list').innerHTML=rs.map(restCard).join('')||'<div class="empty">ما لقينا نتيجة 😕</div>'}
function restaurantsPage(){shell(`<div class="search">🔎 <input id="q" placeholder="ابحث عن مطعم..." oninput="restaurantsDraw()"></div><div class="grid" id="list"></div>`,'المطاعم','rest');restaurantsDraw()}function restaurantsDraw(){let q=(document.getElementById('q')?.value||'').toLowerCase();document.getElementById('list').innerHTML=restaurants.filter(r=>r.name.toLowerCase().includes(q)||r.cat.toLowerCase().includes(q)).map(restCard).join('')}
function restaurantPage(){let id=+(new URLSearchParams(location.search).get('id')||1),r=restaurants.find(x=>x.id===id)||restaurants[0];shell(`<section class="restaurantHero"><div class="row"><div><span class="tag">${r.cat}</span><h1>${r.name}</h1><p class="muted">⭐ ${r.rating} · ${r.time} · توصيل ${money(r.fee)}</p></div><div style="font-size:55px">${r.emoji}</div></div></section><div class="search">🔎 <input id="q" placeholder="ابحث داخل المنيو..." oninput="menuDraw()"></div><div id="items"></div>`,'وصّلني','rest');window.currentRest=r;menuDraw()}
function menuDraw(){let r=window.currentRest,q=(document.getElementById('q')?.value||'').toLowerCase();document.getElementById('items').innerHTML=r.items.filter(i=>!q||i[0].toLowerCase().includes(q)).map((i,n)=>`<div class="item"><div class="food">${i[3]}</div><div class="grow"><b>${i[0]}</b><p class="muted">${i[1]}</p><div class="price">${money(i[2])}</div></div><button class="btn dark" onclick="addItem(${r.id},${n})">أضف</button></div>`).join('')||'<div class="empty">ماكو صنف بهذا الاسم</div>'}
function addItem(rid,idx){let r=restaurants.find(x=>x.id===rid),i=r.items[idx],c=cart();if(c.length&&c[0].restaurantId!==rid)return confirm('السلة تحتوي من مطعم آخر. تبديل المطعم؟')?(put('cart',[]),addItem(rid,idx)):null;let x=c.find(x=>x.itemId===`${rid}-${idx}`);x?x.qty++:c.push({restaurantId:rid,itemId:`${rid}-${idx}`,restaurant:r.name,name:i[0],desc:i[1],price:i[2],emoji:i[3],qty:1});put('cart',c);location.href='cart.html'}
function cartPage(){let c=cart();if(!c.length){shell('<div class="empty">🛒<h2>السلة فارغة</h2><p class="muted">اختار مطعم وابدأ طلبك</p><a class="btn dark" href="restaurants.html">تصفح المطاعم</a></div>','السلة');return}let subtotal=c.reduce((s,x)=>s+x.price*x.qty,0),fee=restaurants.find(r=>r.id===c[0].restaurantId)?.fee||2000,total=subtotal+fee,p=profile();shell(`<h2>سلة ${c[0].restaurant}</h2>${c.map(x=>`<div class="item"><div class="food">${x.emoji}</div><div class="grow"><b>${x.name}</b><div>${money(x.price)}</div></div><button class="btn light" onclick="chg('${x.itemId}',-1)">−</button><b>${x.qty}</b><button class="btn light" onclick="chg('${x.itemId}',1)">+</button></div>`).join('')}<div class="card"><div class="row"><span>المجموع الفرعي</span><b>${money(subtotal)}</b></div><div class="row"><span>التوصيل</span><b>${money(fee)}</b></div><hr><div class="row"><strong>الإجمالي</strong><strong>${money(total)}</strong></div></div><div class="card form"><h2>بيانات التوصيل</h2><input id="name" value="${p.name||''}" placeholder="الاسم الكامل"><input id="phone" value="${p.phone||''}" placeholder="رقم الهاتف"><textarea id="address" rows="3" placeholder="العنوان بالتفصيل">${p.address||''}</textarea><h3>طريقة الدفع</h3><div class="pay"><label><input type="radio" name="pay" value="cash" checked> 💵 كاش</label><label><input type="radio" name="pay" value="card"> 💳 ماستر كارد</label></div><button class="btn dark full" onclick="placeOrder(${subtotal},${fee},${total})">تأكيد الطلب — ${money(total)}</button></div>`,'السلة')}
function chg(id,d){let c=cart(),x=c.find(x=>x.itemId===id);x.qty+=d;put('cart',c.filter(x=>x.qty>0));cartPage()}
function placeOrder(subtotal,fee,total){let name=document.getElementById('name').value.trim(),phone=document.getElementById('phone').value.trim(),address=document.getElementById('address').value.trim();if(!name||!phone||!address)return alert('كمل معلومات التوصيل أولاً');let pay=document.querySelector('[name=pay]:checked').value;if(pay==='card'&&!confirm('سيتم اختيار الدفع بالماستر. ربط بوابة الدفع الحقيقية يتم عند إضافة مفاتيح الدفع الخاصة بالمشروع. استمرار؟'))return;let c=cart(),p={name,phone,address};put('profile',p);let o=orders();o.unshift({id:'WD-'+Date.now().toString().slice(-7),restaurant:c[0].restaurant,restaurantId:c[0].restaurantId,items:c,subtotal,fee,total,pay,name,phone,address,status:'تم استلام الطلب',createdAt:new Date().toISOString(),date:new Date().toLocaleString('ar-IQ')});put('orders',o);put('cart',[]);location.href='orders.html'}
function statusStep(s){let map={'تم استلام الطلب':1,'قيد التحضير':2,'جاهز':3,'مع المندوب':4,'بالطريق':4,'تم التوصيل':5,'ملغي':0};return map[s]||1}
function ordersPage(){let o=orders();shell(o.length?o.map(x=>{let step=statusStep(x.status);return `<article class="order"><div class="row"><b>#${x.id}</b><span class="status">${x.status}</span></div><h3>${x.restaurant}</h3><p>${x.items.map(i=>i.name+' × '+i.qty).join('، ')}</p><div class="progress">${[1,2,3,4].map(n=>`<span class="${step>=n?'done':''}"></span>`).join('')}</div><div class="row"><b>${money(x.total)}</b><span class="muted">${x.date}</span></div><button class="btn light" onclick="repeatOrder('${x.id}')">🔁 إعادة الطلب</button></article>`}).join(''):'<div class="empty">📦<h2>ما عندك طلبات بعد</h2><a class="btn dark" href="restaurants.html">ابدأ أول طلب</a></div>','طلباتي','orders')}
function repeatOrder(id){let o=orders().find(x=>x.id===id);if(!o)return;put('cart',o.items.map(i=>({...i})));location.href='cart.html'}
function profileModal(){let p=profile();document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="m"><div class="modalBox"><div class="row"><h2>بياناتي</h2><button class="btn light" onclick="m.remove()">✕</button></div><input id="pn" value="${p.name||''}" placeholder="الاسم"><input id="pp" value="${p.phone||''}" placeholder="رقم الهاتف"><textarea id="pa" rows="3" placeholder="العنوان">${p.address||''}</textarea><button class="btn dark full" onclick="saveP()">حفظ</button></div></div>`)}function saveP(){put('profile',{name:pn.value.trim(),phone:pp.value.trim(),address:pa.value.trim()});document.getElementById('m').remove();accountPage()}
function accountPage(){let p=profile(),o=orders(),active=o.find(x=>!['تم التوصيل','ملغي'].includes(x.status)),del=o.filter(x=>x.status==='تم التوصيل').length,spent=o.filter(x=>x.status!=='ملغي').reduce((s,x)=>s+x.total,0),name=p.name||'ضيفنا العزيز';shell(`<section class="accountHero"><div class="avatar">${name==='ضيفنا العزيز'?'👤':name[0]}</div><div class="accountInfo"><div>مرحباً 👋</div><h1>${name}</h1><p>${p.phone||'أكمل بياناتك حتى نسهّل عليك الطلب'}</p></div><button class="editCircle" onclick="profileModal()">✎</button></section>${active?`<section class="liveOrder"><div class="liveTop"><b>🟢 طلبك الحالي</b><span class="status">${active.status}</span></div><div class="liveBody"><div><b>#${active.id}</b><p>${active.restaurant}</p></div><a href="orders.html">‹</a></div><div class="progress">${[1,2,3,4].map(n=>`<span class="${statusStep(active.status)>=n?'done':''}"></span>`).join('')}</div></section>`:''}<div class="quickGrid"><a class="quick" href="orders.html"><span>📦</span><b>طلباتي</b><small>${o.length} طلب</small></a><button class="quick" onclick="profileModal()"><span>📍</span><b>عناويني</b><small>${p.address?'عنوان محفوظ':'أضف عنوانك'}</small></button><a class="quick" href="cart.html"><span>🛒</span><b>السلة</b><small>${count()} أصناف</small></a><a class="quick" href="restaurants.html"><span>🔁</span><b>اطلب مرة ثانية</b><small>اختار من المطاعم</small></a></div><section class="statsCard"><div><strong>${o.length}</strong><span>كل الطلبات</span></div><div><strong>${del}</strong><span>مستلمة</span></div><div><strong>${money(spent)}</strong><span>المشتريات</span></div></section><section class="accountSection"><h2>حسابي</h2><div class="menuList"><button onclick="profileModal()"><span>👤</span><div><b>المعلومات الشخصية</b><small>الاسم ورقم الهاتف</small></div><i>‹</i></button><button onclick="profileModal()"><span>📍</span><div><b>عنوان التوصيل</b><small>${p.address||'أضف عنوانك'}</small></div><i>‹</i></button><button onclick="alert('تقدر تختار كاش أو ماستر عند تأكيد الطلب')"><span>💳</span><div><b>طرق الدفع</b><small>كاش أو ماستر كارد</small></div><i>‹</i></button><button onclick="alert('نظام العروض والكوبونات جاهز للربط مع لوحة الإدارة')"><span>🎁</span><div><b>العروض والكوبونات</b><small>قريباً</small></div><i>‹</i></button></div></section><section class="accountSection"><h2>الدعم</h2><div class="menuList"><button onclick="alert('سيتم ربط واتساب/دردشة خدمة العملاء لاحقاً')"><span>💬</span><div><b>خدمة العملاء</b><small>مساعدة بخصوص الطلب</small></div><i>‹</i></button><button onclick="alert('مركز المساعدة')"><span>❓</span><div><b>مركز المساعدة</b><small>الأسئلة الشائعة</small></div><i>‹</i></button></div></section>`,'حسابي','account')}
function adminPage(){let o=orders(),sales=o.filter(x=>x.status!=='ملغي').reduce((s,x)=>s+x.total,0);shell(`<section class="hero"><h1>لوحة الإدارة</h1><p>إدارة الطلبات والمطاعم والمندوبين</p></section><div class="statgrid"><div class="stat">الطلبات<h2>${o.length}</h2></div><div class="stat">المبيعات<h2>${money(sales)}</h2></div></div><h2>الأنظمة</h2><div class="grid"><a class="card" href="restaurant-panel.html">🏪 طلبات المطاعم</a><a class="card" href="driver.html">🛵 المندوبين</a><a class="card" href="restaurants.html">🍽️ واجهة الزبون</a><a class="card" href="orders.html">📦 الطلبات</a></div>`,'الإدارة')}
function panelPage(){let o=orders();shell(`<h2>طلبات المطعم</h2>${o.map(x=>`<article class="order"><div class="row"><b>#${x.id}</b><span class="status">${x.status}</span></div><h3>${x.restaurant}</h3><p>${x.items.map(i=>i.name+' × '+i.qty).join('، ')}</p><p class="muted">${x.name} · ${x.phone}<br>${x.address}</p>${x.status==='تم استلام الطلب'?`<button class="btn dark" onclick="setStatus('${x.id}','قيد التحضير')">قبول الطلب وبدء التحضير</button>`:x.status==='قيد التحضير'?`<button class="btn dark" onclick="setStatus('${x.id}','جاهز')">الطلب جاهز</button>`:x.status==='جاهز'?`<button class="btn dark" onclick="setStatus('${x.id}','بانتظار المندوب')">تجهيز للتسليم</button>`:''}</article>`).join('')||'<div class="empty">لا توجد طلبات</div>','لوحة المطعم')}
function driverPage(){let o=orders();shell(`<h2>طلبات المندوب</h2>${o.map(x=>`<article class="order"><div class="row"><b>#${x.id}</b><span class="status">${x.status}</span></div><h3>${x.restaurant}</h3><p>${x.address}</p>${['جاهز','بانتظار المندوب'].includes(x.status)?`<button class="btn dark" onclick="setStatus('${x.id}','مع المندوب')">استلام الطلب</button>`:x.status==='مع المندوب'?`<button class="btn dark" onclick="setStatus('${x.id}','بالطريق')">أنا بالطريق</button>`:x.status==='بالطريق'?`<button class="btn dark" onclick="setStatus('${x.id}','تم التوصيل')">تم التوصيل</button>`:''}</article>`).join('')||'<div class="empty">لا توجد طلبات</div>','المندوب')}
function setStatus(id,s){let o=orders(),x=o.find(x=>x.id===id);if(x){x.status=s;put('orders',o);location.reload()}}
function loginPage(){document.getElementById('app').innerHTML=`<div class="app"><main class="main"><section class="hero"><h1>وصّلني</h1><p>دخول الأنظمة الداخلية</p></section><div class="card form"><select id="role"><option value="admin">الإدارة</option><option value="restaurant">المطعم</option><option value="driver">المندوب</option></select><input id="pin" type="password" placeholder="PIN تجريبي 1234"><button class="btn dark" onclick="login()">دخول</button><a class="btn light" href="index.html">رجوع للزبون</a></div></main></div>`}function login(){if(pin.value!=='1234')return alert('PIN غير صحيح');let r=role.value;location.href=r==='admin'?'admin.html':r==='restaurant'?'restaurant-panel.html':'driver.html'}
let page=location.pathname.split('/').pop()||'index.html';({ 'index.html':home,'':home,'restaurants.html':restaurantsPage,'restaurant.html':restaurantPage,'cart.html':cartPage,'orders.html':ordersPage,'account.html':accountPage,'admin.html':adminPage,'restaurant-panel.html':panelPage,'driver.html':driverPage,'login.html':loginPage}[page]||home)();
